<?php

namespace AppBundle\Repository;

/**
 * Description of TypZdarzeniaRepository
 *
 * @author Mateusz Błaszczak
 */

/**
 * TypZdarzeniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypZdarzeniaRepository extends \Doctrine\ORM\EntityRepository
{
}
